// <auto-generated />
using System;
using EF.Core.Tutorial.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF.Core.Tutorial.Migrations
{
    [DbContext(typeof(KeyGenContext))]
    [Migration("20200809123213_CreateKeyGenDB_V1")]
    partial class CreateKeyGenDB_V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF.Core.Tutorial.Models.Randomizer", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("KeyGen")
                        .HasColumnType("int");

                    b.HasKey("UniqueId");

                    b.ToTable("Randomizers");
                });
#pragma warning restore 612, 618
        }
    }
}
